# The release pipeline will run only if all jobs in the test pipeline are successful
stages:
    - test
    - release

before_script:
    - npm install

node:8:
    image: node:8
    stage: test
    script:
        - npm test

node:10:
    image: node:10
    stage: test
    script:
        - npm test

node:11:
    image: node:11
    stage: test
    script:
        - npm test

publish:
    image: node:8
    stage: release
    script:
        - npx semantic-release
