---
plugins:
    - - '@semantic-release/commit-analyzer'
      - preset: angular
    - - '@semantic-release/release-notes-generator'
      - preset: angular
    - - '@semantic-release/changelog'
      - changelogFile: CHANGELOG.md
    - - '@semantic-release/npm'
      - tarballDir: dist
    - - semantic-release-vsce
      - packageVsix: dist/vscode-workspace-manager.vsix
    - - '@semantic-release/github'
      - assets:
            - dist/*.tgz
            - path: dist/vscode-workspace-manager.vsix
              label: vscode-workspace-manager.vsix
    - - '@semantic-release/git'
      - assets:
            - dist/**/*.{js,css}
            - docs
            - package.json
        message: 'chore(release): ${nextRelease.version} [skip ci] ${nextRelease.notes}'
