language: node_js

node_js:
    - 11
    - 11
    - 10
    - 8

before_install:
    - yarn

jobs:
    include:
        # Define the release stage that runs semantic-release
        - stage: release
          # require the branch name to be master (note for PRs this is the base branch name)
          if: branch = master
          node_js: lts/*
          # Advanced: optionally overwrite your default `script` step to skip the tests
          # script: skip
          deploy:
              provider: script
              skip_cleanup: true
              script:
                  - yarn run release
