name: CI

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master
            - develop

jobs:
    build:
        name: ${{ format('Run Test Node.js {0}', matrix.node) }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: ['12', '11', '10', '8']
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: ${{ format('Set Node.js {0}', matrix.node) }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: Test
              run: |
                  npm install
                  npm run test

    release:
        name: Release
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Set Node.js 12
              uses: actions/setup-node@v1
              with:
                  node-version: 12

            - name: Release
              if: github.event_name == 'pull_request'
              run: npm run release
              env:
                  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
                  VSCE_TOKEN: ${{secrets.VSCE_TOKEN}}
                  GH_TOKEN: ${{secrets.GH_TOKEN}}

    publish-gpr:
        name: Publish GitHub Packages
        needs: [build, release]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Set Node.js 12
              uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.github.com/
                  scope: '@design4pro'

            - name: Publish
              if: github.event_name == 'pull_request'
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
